### PR TITLE
Update rps.js

### PR DESCRIPTION
**Pull request by Stubbers1**
more rps

### CODE REVIEW

**Comment by DarkVoid19** [comment]
This seems like a bad idea

**Comment by Stubbers1** [comment]
please as waiting is bad

**Review by DarkVoid19 — CHANGES_REQUESTED** [review]
1 second is too low for a cooldown

**Review by DarkVoid19 — CHANGES_REQUESTED** [review]
Nope

**Review by DarkVoid19 — APPROVED** [review]
This works

**Pull request merged**
